### ISSUE TITLE
Scraping de usuarios de indreams.me

### ISSUE THREAD

**Issue by carloitaben** [dreamiverso/bot#12]
Ahora mismo la implementación del scraper es muy sencilla y solo trae información sobre la `persona`: niveles y auras. Creo que necesitamos algo más flexible:

- [ ] Evitar que explote si el nivel del usuario es menor a 5 (no tiene auras)
- [ ] Evitar que explote si el `querySelector` no encuentra elementos en el DOM (devería devolver `undefined`)
- [ ] Montar un `type` del scrape de usuario: un objeto que puede devolver todo lo scrapeable
- [ ] Testear con diferentes cuentas: quizás algunas tienen más info que otras (algunos perfiles tienen info de cuentas enlazadas de Twitch)
- [ ] Plantear una API bonita, que deje elegir qué página scrapear. Estaría bien tener varios métodos: uno por página de indreams. Por ejemplo, el usuario tiene el index, /creations, /coments… Todo eso debería ser scrapeable

**Comment by Carloitaben** [comment]
Podríamos usar este método en vez de `innerText`
 https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

**Comment by Carloitaben** [comment]
Esto será un proyecto aparte
