### ISSUE TITLE
Scraping de creaciones de indreams.me

### ISSUE THREAD

**Issue by carloitaben** [dreamiverso/bot#13]
Al igual que con los usuarios, las creaciones de indreams deberían ser scrapeables

- [ ] Colecciones
- [ ] Sueños
- [ ] Escenas
- [ ] Elementos

Quizás estaría bien empezar por sueños, para ver si podemos enlazar canales de proyecto con sueños y mandar notificaciones con stats y demás

**Comment by Carloitaben** [comment]
Esto será un proyecto aparte
